[build]
  builder = "nixpacks"
  buildCommand = "cd backend && npm install"
  startCommand = "cd backend && node server.js"

[deploy]
  startCommand = "node backend/server.js"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 60
  restartDelay = 5
  restartLimit = 5
  
[environments]
  [environments.production]
    # Server Configuration
    NODE_ENV = "production"
    PORT = "3000"
    HOST = "0.0.0.0"
    
    # Database Configuration
    # MONGODB_URI = "your_mongodb_uri"
    
    # Security
    # JWT_SECRET = "your_jwt_secret"
    # JWT_EXPIRES_IN = "90d"
    # JWT_COOKIE_EXPIRES_IN = "90"
    
    # Rate Limiting
    RATE_LIMIT_WINDOW_MS = "3600000"  # 1 hour
    RATE_LIMIT_MAX = "100"
    
    # CORS
    CORS_ORIGIN = "https://28degreeswest.com,https://www.28degreeswest.com"
    
    # Logging
    NODE_ENV = "production"
    LOG_LEVEL = "info"
    
    # Email (if applicable)
    # EMAIL_FROM = "28 Degrees West <noreply@28degreeswest.com>"
    # SENDGRID_USERNAME = "apikey"
    # SENDGRID_PASSWORD = "your_sendgrid_api_key"
    
    # Stripe (if applicable)
    # STRIPE_SECRET_KEY = "your_stripe_secret_key"
    # STRIPE_WEBHOOK_SECRET = "your_stripe_webhook_secret"
    
    # Frontend URL (for CORS and redirects)
    FRONTEND_URL = "https://28degreeswest.com"
