[build]
  builder = "nixpacks"
  buildCommand = "cd backend && npm install"
  startCommand = "cd backend && node server.js"

[deploy]
  startCommand = "node server.js"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 100
  restartDelay = 5
  restartLimit = 5
