name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://28degreeswest.com
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit --prefer-offline

      - name: Build
        run: |
          echo "Building with environment:"
          echo "VITE_API_URL: ${VITE_API_URL:-Not set}"
          echo "VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN:-Not set}"
          echo "NODE_ENV: ${NODE_ENV:-Not set}"
          npm run build
        env:
          NODE_ENV: production
          # API Configuration
          VITE_API_BASE_URL: ${{ secrets.VITE_API_URL || 'https://api.28degreeswest.com' }}
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://api.28degreeswest.com' }}
          
          # Firebase Configuration
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN || '28degreeswest.com' }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET || '28degreeswest.appspot.com' }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          
          # Third-party Services
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
          VITE_GA_TRACKING_ID: ${{ secrets.VITE_GA_TRACKING_ID }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          
          # Application Settings
          VITE_ADMIN_EMAIL: ${{ secrets.VITE_ADMIN_EMAIL }}
          PUBLIC_URL: /

      - name: Create CNAME file
        run: |
          echo "28degreeswest.com" > dist/CNAME
          echo "CNAME file created with content:"
          cat dist/CNAME

      - name: Verify build output
        run: |
          echo "Build output directory contents:"
          ls -la dist/
          echo -e "\nindex.html head section:"
          grep -A 20 '<head' dist/index.html || true
          echo -e "\nCNAME file:"
          cat dist/CNAME || echo "No CNAME file found"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: 'vite'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: https://28degreeswest.com
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          keep_history: true
          full_commit_message: 'Deploy to GitHub Pages'

      - name: Verify deployment
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Deployment status: ${{ steps.deployment.outputs.status }}"
