name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          # Create docs directory if it doesn't exist
          mkdir -p docs
          # Copy built files to docs directory
          cp -r dist/* docs/
          # Create .nojekyll file to ensure all files are served
          touch docs/.nojekyll

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/
          git commit -m "Deploy to GitHub Pages [skip ci]" || echo "No changes to commit"
          git push origin main
